<?php

return [
    [
        'name' => 'classname',
        'title' => '渲染文本框元素',
        'type' => 'string',
        'content' => [],
        'value' => '.editor',
        'rule' => 'required',
        'msg' => '',
        'tip' => '用于对指定的元素渲染，一般情况下无需修改',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'fullmode',
        'title' => '是否启用完整URL路径模式',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'autoHeightEnabled',
        'title' => '自动高度',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'minFrameHeight',
        'title' => '编辑器最小高度',
        'type' => 'string',
        'content' => [],
        'value' => '300',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'initialFrameHeight',
        'title' => '编辑器初始高度',
        'type' => 'string',
        'content' => [],
        'value' => '300',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'toolbar',
        'title' => '编辑器工具栏',
        'type' => 'text',
        'content' => [],
        'value' => 'source | undo redo | bold italic underline strikethrough table | superscript subscript | forecolor backcolor | removeformat | insertorderedlist insertunorderedlist | selectall cleardoc paragraph | fontfamily fontsize | justifyleft justifycenter justifyright justifyjustify | link unlink | emotion image video file  | map  | horizontal print preview fullscreen drafts formula',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isdompurify',
        'title' => '是否启用加强的HTML过滤',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'allowiframeprefixs',
        'title' => '设定允许iframe的白名单',
        'type' => 'array',
        'content' => [],
        'value' => [],
        'rule' => 'required',
        'favisible' => 'isdompurify=1',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'baidumapkey',
        'title' => '百度地图API密钥',
        'type' => 'string',
        'content' => [],
        'value' => '11111111',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'baidumapcenter',
        'title' => '百度地图中心点经纬度',
        'type' => 'string',
        'content' => [],
        'value' => '116.404413,39.903536',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => '百度地图API密钥申请地址：http://lbsyun.baidu.com/apiconsole/key<br>百度地图经纬度坐标获取：https://api.map.baidu.com/lbsapi/getpoint/index.html',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
