<?php

return [
    [
        'name' => 'captchaType',
        'title' => '验证码类型',
        'type' => 'radio',
        'group' => '',
        'visible' => '',
        'content' => [
            'clickWord' => '点选验证',
            'blockPuzzle' => '滑动验证',
        ],
        'value' => 'blockPuzzle',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captchaMode',
        'title' => '展示模式',
        'type' => 'radio',
        'group' => '',
        'visible' => '',
        'content' => [
            'pop' => '弹窗',
            'fixed' => '内嵌',
        ],
        'value' => 'pop',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'preRender',
        'title' => '预渲染',
        'type' => 'radio',
        'group' => '',
        'visible' => '',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'font',
        'title' => '默认字体',
        'type' => 'file',
        'content' => [],
        'value' => '/assets/fonts/SourceHanSansK-Regular.ttf',
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果出现乱码，可以使用自定义字体',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'watermark',
        'title' => '水印配置',
        'type' => 'array',
        'content' => [],
        'value' => [
            'fontsize' => '12',
            'color' => '#ffffff',
            'text' => '吉尼斯盛投',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
